version: "3.8"

services:

  nutribot:
    build: .
    container_name: nutribot
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - langfuse
    restart: unless-stopped

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    container_name: langfuse
    depends_on:
      - postgres
    env_file:
      - langfuse/docker.env
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    container_name: langfuse-db
    restart: always
    volumes:
      - langfuse-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse

volumes:
  langfuse_db:
